version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    versioning-strategy: "increase"
    groups:
      python-production:
        dependency-type: "production"
      python-development:
        dependency-type: "development"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "django"
        versions: [">=5.0.0"]
      - dependency-name: "django-ninja"
        versions: [">=1.2.0"]
      - dependency-name: "opentelemetry-sdk"
        versions: [">=1.31.0"]
      - dependency-name: "opentelemetry-instrumentation"
        versions: [">=1.31.0"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
