version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    groups:
      python-production:
        dependency-type: "production"
      python-development:
        dependency-type: "development"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
      - dependency-name: "django-ninja"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
